# -*- coding: utf-8 -*-
"""1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3HJ2zf3aUv6feNu1x8qsS6FOt5njrLy
"""



def check_anagram(str1,str2):
  str1=str1.replace(" ","")
  str2=str2.replace(" ","")
  if len(str1)==len(str2):
    return sorted(str1)==sorted(str2)

  return false
string1=input("s=")
string2=input("t=")
if check_anagram(string1,string2):
  print("True")
else:
  print("false")