# -*- coding: utf-8 -*-
"""7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6_f1f90W924AycgcMbzICShphXS424c
"""

def fact(N):
  for i in range(2,N+1):
    if(N%i==0):
      if isprime(i):
        return i

def isprime(n):
  if n<=1:
    return false
  for i in range(2, int(n**0.5)+1):
    if n%i==0:
      return false
  return True



N=int(input("Enter the number of items:"))
for i in range(1,N+1):
  R=int(input(f"Enter the MRP of items {i}:"))
  f=fact(R)
  p=R-f
  print("Amount Roy pays= Rs.",p)
  print("Amount Alfie pays= Rs.",f)