# -*- coding: utf-8 -*-
"""8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1564NwJvOC20DA-O8EvYlTGsHJ-CCwS8m
"""

def count_frequencies(l):
    l=l.replace(" ","")
    freq = {}
    for i in l:
        if i in freq:
            freq[i] += 1
        else:
            freq[i] = 1
    return freq


list=input("Enter the list:")
frequencies = count_frequencies(list)
print(frequencies)