# -*- coding: utf-8 -*-
"""question 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEPRVZAEe6tD5lnEfdEGyE5itFQly3tK
"""



"""question no 1"""

s= input("enter the string s:")
t = input("enter the string t :")
s1=s.lower()
t1=t.lower()
print(s1)
print(t1)
if (sorted(s1)==sorted(t1)):
  print("they are anagrams")
else:
    print("they are not anagrams")



